# Generated by Django 2.0.6 on 2018-07-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('songBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SongSimilarity_right', to='song.Song')),
                ('songCompare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SongSimilarity_left', to='song.Song')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='songsimilarity',
            unique_together={('songBase', 'songCompare')},
        ),
    ]
