# Generated by Django 2.0.6 on 2018-07-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songSimilarity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songsimilarity',
            old_name='similarity',
            new_name='cosine',
        ),
    ]
