# Generated by Django 2.0.6 on 2018-07-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_index=True, default='7f3e4dd87cd311e8a4a98db90271ba7c', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
