# Generated by Django 2.0.6 on 2018-07-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, default='9f89780e7cd511e8a4a98db90271ba7c', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
