# Generated by Django 2.0.6 on 2018-07-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180630_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(db_index=True, default='0521d97c7cd611e8a4a98db90271ba7c', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
